添加邮件通知
IanSmith123/ucas-covid19 pull request #24
Opened 2020-12-22 04:13 UTC by T-winkle

添加邮件通知功能。

2020-12-22 04:57 UTC, IanSmith123 requested changes
感谢PR，我对部分内容做出了修改建议，请综合考虑我的建议和你自己的想法对代码做出修改。:)

2020-12-22 04:57 UTC, IanSmith123 commented on sub.py
> +        smtp = smtplib.SMTP_SSL("smtp.qq.com", 465)
建议给用户自定义 smtp服务器端口和地址的参数，用户可能不使用 qq 邮箱。
建议如果用户没指定smtp服务器地址就默认使用QQ邮箱，如果用户指定了服务器地址和端口就是用用户指定的配置。

2020-12-22 04:57 UTC, IanSmith123 commented on sub.py
> +    send_email(sender_email, sender_email_passwd, receiver_email, result.get('m'), new_daily)
建议给用户提供一个选项，使用server酱通知或者使用邮箱通知，目前这样写也没问题，如果用户没配置某一个会导致发送失败，不过看起来不够 pythonic :)

2020-12-22 04:57 UTC, IanSmith123 commented on README.md
> +  - `SENDER_EMAIL`: 发送通知打卡通知邮件的邮箱（可选）
因为使用此项目的同学并非都是计算机专业的，请把文档写得更详细一点。建议在此注明如果想要使用邮件通知，那么三者都需要同时写，并且提醒用户部分邮箱需要开启客户端smtp收信服务，填写的密码可能不同于邮箱的登录密码。

2020-12-22 04:57 UTC, IanSmith123 commented on sub.py
> +        print("邮件发送失败")
请验证一下如果邮件发送失败抛出的异常会不会暴露用户的邮件地址信息。因为github actions 的日志默认情况下是对所有人可见的。

2020-12-22 12:47 UTC, T-winkle commented on sub.py
> +        smtp = smtplib.SMTP_SSL("smtp.qq.com", 465)
我有考虑到这个问题，但是想到大部分人应该都会有qq邮箱，所以就固定为了qq的smtp服务器。我时间有限，所以没有做进一步的处理，有时间我修改一下。

2020-12-22 12:48 UTC, T-winkle commented on sub.py
> +    send_email(sender_email, sender_email_passwd, receiver_email, result.get('m'), new_daily)
确实不够优雅，但其实是为了保持和server酱的写法一直。

2020-12-22 12:48 UTC, T-winkle commented on README.md
> +  - `SENDER_EMAIL`: 发送通知打卡通知邮件的邮箱（可选）
确实描述的不太清楚，高些指正。

2020-12-22 12:50 UTC, T-winkle commented on sub.py
> +        print("邮件发送失败")
可能会存在这个问题，把异常输出的语句直接删除是否可行？

2020-12-22 13:20 UTC, IanSmith123 commented on sub.py
> +        print("邮件发送失败")
可以直接删除，也可以判断是否在 debug 状态决定是否输出，我在 https://github.com/IanSmith123/ucas-covid19/blob/53b199106a775f9bac8faeae1974363fae64ffd6/sub.py#L14 定义了一个 debug变量，如果debug为 True，那么认为是在安全的环境下，可以打印敏感信息，如果 debug为False，那么就不输出较为敏感的日志，在github actions运行的情境下， debug为False

2020-12-22 13:20 UTC, IanSmith123 commented on sub.py
> +    send_email(sender_email, sender_email_passwd, receiver_email, result.get('m'), new_daily)
那就保持这样吧，没有什么太大的问题。

2020-12-22 13:22 UTC, T-winkle commented on sub.py
> +        print("邮件发送失败")
好的我修改一下。

2020-12-22 14:06 UTC, T-winkle commented on README.md
> +  - `SENDER_EMAIL`: 发送通知打卡通知邮件的邮箱（可选）
如果用户并非都是计算机专业的同学，建议说明使用步骤中的start并非必须步骤。

2020-12-23 07:37 UTC, IanSmith123 approved these changes
LGTM

2020-12-23 07:37 UTC, merged

2020-12-23 07:44 UTC, IanSmith123 commented
已合并，感谢PR。